version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $nodeapp:latest .
  publish-latest:
    environment:
      nodeapp: building-on-ci
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "docker login -u "$DOCKERHUB_LOGIN" -p $DOCKER_PASSWORD
            docker push $nodeapp:latest
