version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: docker build -t nodeapp .
      - run: docker tag nodeapp aseelibrahimm/nodeapp:lts
      - run: docker login -u aseelibrahimm -p aseel2000
      - run: docker push aseelibrahimm/nodeapp:lts
